wild : sync patches with upsream (wild kernels repo) bulid : add support for building with thin lto or full lto
Signed-off-by: nullptr-t-oss <127822226+nullptr-t-oss@users.noreply.github.com>

diff --git a/.github/kernel/action.yml b/.github/kernel/action.yml
--- a/.github/kernel/action.yml
+++ b/.github/kernel/action.yml
@@ -32,6 +32,10 @@ inputs:
     required: false
     type: string
     default: O2  # Choices: O2 or O3
+  lto:
+    required: false
+    type: string
+    default: Thin  # Choices: Thin or Full
   clang_version:
     required: false
     type: string
@@ -378,8 +382,7 @@ runs:
             exit 1
             ;;
         esac
-        patch -p1 --forward < ksun_susfs_latest.patch || true
-        cd ../common
+        cd $COMMON
         if [ "${{ env.ANDROID_RELEASE }}" = "android15" ] && [ "${{ env.KERNEL_VER }}" = "6.6" ]; then
           if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c; then
             sed -i '/#include <trace\/hooks\/blk.h>/a #include <trace\/hooks\/fs.h>' ./fs/namespace.c
@@ -395,22 +398,67 @@ runs:
             fake_patched=1
           fi
         fi
+
+        if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
+            echo "#include <linux/dma-buf.h> Line not found. Adding missing header"
+            sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
+          fi
+          
+          if ! grep -qxF '#include <linux/zswap.h>' ./mm/memory.c; then
+            echo "#include <linux/zswap.h> Line not found. Adding missing header"
+            sed -i '/#include <linux\/sched\/sysctl.h>/a #include <linux\/zswap.h>' ./mm/memory.c
+          fi
+          
+          if grep -qF 'if (vma->vm_end > last_vma_end)' ./fs/proc/task_mmu.c && ! grep -qxF 'SUSFS_IS_INODE_SUS_MAP' ./fs/proc/task_mmu.c; then
+            echo "Temporarily expand the `last_vma_end` `if` block to fix a matching issue."
+            perl -i -0pe 's/\t\t\tif \(vma->vm_end > last_vma_end\)\n\t\t\t\tsmap_gather_stats\(vma, &mss, last_vma_end\);/\t\t\tif (vma->vm_end > last_vma_end) {\n\t\t\t\tsmap_gather_stats(vma, \&mss, last_vma_end);\n\t\t\t\tlast_vma_end = vma->vm_end;\n\t\t\t}/' ./fs/proc/task_mmu.c
+            fake_patched_expand=1
+          fi
+        fi
+
         if [ "${{ env.ANDROID_RELEASE }}" = "android12" ] && [ "${{ env.KERNEL_VER }}" = "5.10" ]; then
           if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
             echo "vma_pages Line not found. Fake Patching!"
             fake_patched=1
           fi
         fi
+
         if [ "${{ env.ANDROID_RELEASE }}" = "android13" ] && [ "${{ env.KERNEL_VER }}" = "5.15" ]; then
           if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
             echo "vma_pages Line not found. Fake Patching!"
             fake_patched=1
+          fi
+
+          if grep -qxF '#include <linux/swap_slots.h>' ./mm/memory.c; then
+            echo "#include swap_slots.h> Line found. Deleting header."
+            sed -i '/#include <linux\/swap_slots.h>/d' ./mm/memory.c
+            fake_patched=1
+          fi
+        fi
+
+        if [ "${{ env.ANDROID_RELEASE }}" = "android14" ] && [ "${{ env.KERNEL_VER }}" = "6.1" ]; then
+          if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
+            echo "vma_pages Line not found. Fake Patching!"
+            fake_patched=1
+          fi
+          
+          if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
+            echo "#include <linux/dma-buf.h> Line not found. Adding missing header"
+            sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
           fi
         fi
 
         patch -p1 < 50_add_susfs_in_${{ env.SUSFS_KERNEL_BRANCH }}.patch
 
         # Revert Fake kernel patch
+        if [ "$fake_patched_expand" = 1 ]; then
+          if [ "${{ env.ANDROID_RELEASE }}" = "android15" ] && [ "${{ env.KERNEL_VER }}" = "6.6" ]; then
+            if grep -qF 'if (vma->vm_end > last_vma_end) {' ./fs/proc/task_mmu.c && ! grep -qxF 'SUSFS_IS_INODE_SUS_MAP' ./fs/proc/task_mmu.c; then
+              perl -i -0pe 's/\t\t\tif \(vma->vm_end > last_vma_end\) \{\n\t\t\t\tsmap_gather_stats\(vma, &mss, last_vma_end\);\n\t\t\t\tlast_vma_end = vma->vm_end;\n\t\t\t\}/\t\t\tif (vma->vm_end > last_vma_end)\n\t\t\t\tsmap_gather_stats(vma, \&mss, last_vma_end);/' ./fs/proc/task_mmu.c
+            fi
+          fi
+        fi
+
         if [ "$fake_patched" = 1 ]; then
           if [ "${{ env.ANDROID_RELEASE }}" = "android15" ] && [ "${{ env.KERNEL_VER }}" = "6.6" ]; then
             if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
@@ -428,6 +476,11 @@ runs:
             if grep -qxF $'\t\t\tgoto show_pad;' ./fs/proc/task_mmu.c; then
               echo "vma_pages Line found. Revert Fake Patching!"
               sed -i -e 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
+            fi
+
+            if ! grep -qxF '#include <linux/swap_slots.h>' ./mm/memory.c; then
+              echo "#include <linux/swap_slots.h> Line not found. Adding missing header"
+              sed -i '/#include <linux\/vmalloc.h>/a #include <linux\/swap_slots.h>' ./mm/memory.c
             fi
           fi
           if [ "${{ env.ANDROID_RELEASE }}" = "android14" ] && [ "${{ env.KERNEL_VER }}" = "6.1" ]; then
@@ -565,9 +618,22 @@ runs:
         echo "::group::Applying patches from wild kernels..."
         cd "$COMMON"
 
+        KERNEL_VERSION="${{ env.KERNEL_VER }}"
+        MIN_VERSION="5.16"
+
+        patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/optimized_mem_operations.patch"
+        patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/file_struct_8bytes_align.patch"
+        patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/reduce_cache_pressure.patch"
+
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/mem_opt_prefetch.patch"
 
-        sed -e 's/SYM_FUNC_START(__pi_memcmp)/SYM_FUNC_START_WEAK_PI(memcmp)/' -e 's/SYM_FUNC_END(__pi_memcmp)/SYM_FUNC_END_PI(memcmp)/' -e 's/SYM_FUNC_ALIAS_WEAK(memcmp, __pi_memcmp)/EXPORT_SYMBOL_NOKASAN(memcmp)/' "$WILD_KERNEL_PATCHES/common/optimise_memcmp.patch" | patch -p1 --forward
+        if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
+          patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/optimise_memcmp.patch"
+        elif [ "$(printf '%s\n' "$KERNEL_VERSION" "5.11" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
+          sed -e 's/SYM_FUNC_START(__pi_memcmp)/SYM_FUNC_START_WEAK_PI(memcmp)/' -e 's/SYM_FUNC_END(__pi_memcmp)/SYM_FUNC_END_PI(memcmp)/' -e 's/SYM_FUNC_ALIAS_WEAK(memcmp, __pi_memcmp)/EXPORT_SYMBOL_NOKASAN(memcmp)/' "$WILD_KERNEL_PATCHES/common/optimise_memcmp.patch" | patch -p1 --forward
+        else
+          echo "Optimised memcmp patch not found!"
+        fi
 
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/minimise_wakeup_time.patch"
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/int_sqrt.patch"
@@ -576,6 +642,12 @@ runs:
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/add_timeout_wakelocks_globally.patch"
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/f2fs_reduce_congestion.patch"
         patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/reduce_freeze_timeout.patch"
+
+        if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
+          patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/clear_page_16bytes_align.patch"
+        else
+          cat "$WILD_KERNEL_PATCHES/common/clear_page_16bytes_align.patch" | sed -e 's/SYM_FUNC_START_PI(clear_page)/SYM_FUNC_START_PI(__pi_clear_page)/' | patch -p1 -F3 --forward
+        fi
 
         patch -p1 -F3 --forward < "$WILD_KERNEL_PATCHES/common/add_limitation_scaling_min_freq.patch"
         patch -p1 -F3 --forward < "$WILD_KERNEL_PATCHES/common/re_write_limitation_scaling_min_freq.patch"
@@ -678,7 +750,6 @@ runs:
         echo "::endgroup::"
 
     - name: Add Other configs
-      if: env.KERNEL_VER == '5.15'
       shell: bash
       run: |
         set -euo pipefail
@@ -688,31 +759,36 @@ runs:
         ./scripts/config --file arch/arm64/configs/gki_defconfig \
           --enable CONFIG_LRU_GEN_ENABLED
 
+        # Add for Droidspaces support
+        echo "Applying patch to enable SYSVIPC without breaking ABI"
+        case "$BRANCH" in
+          oneplus/sm8850|oneplus/sm8845)
+            patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_a16-6.12.patch"
+            ;;
+          oneplus/sm8550|oneplus/sm7550)
+            patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_1_2_3.patch"
+            ;;
+          oneplus/sm8450|oneplus/sm8475|oneplus/mt6895|oneplus/mt6983|oneplus/mt6789)
+            if [ "$ANDROID_RELEASE" = "android12" ] && [ "$KERNEL_VER" = "5.10" ]; then
+              patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_bypass_a16-6.12_below.patch"
+              patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_abi_padding_for_posix_mqueue.patch"
+            else
+              patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_6_7_8.patch"
+            fi
+            ;;
+          *)
+            patch -p1 --forward < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_6_7_8.patch"
+            ;;
+        esac
+
         ./scripts/config --file arch/arm64/configs/gki_defconfig \
                   --enable CONFIG_SYSVIPC \
                   --enable CONFIG_DEVTMPFS \
                   --enable CONFIG_PID_NS \
-                  --enable CONFIG_POSIX_MQUEUE
-
-        # Add for Droidspaces support
-        # TODO: This patch is not universal add conditions for other kernel versions!
-        #       for now Droidspaces support for kernels other than 5.15 is restricted
-        if patch -R -p1 -s -f --dry-run < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_1_2_3.patch" >/dev/null 2>&1 || \
-           patch -R -p1 -s -f --dry-run < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_3_4_5.patch" >/dev/null 2>&1 || \
-           patch -R -p1 -s -f --dry-run < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_6_7_8.patch">/dev/null 2>&1; then
-          echo "Patch already applied. Skipping."
-        else
-          echo "Applying patch..."
-          if patch -p1 --dry-run < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_1_2_3.patch" > /dev/null 2>&1; then
-            patch -p1 < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_1_2_3.patch"
-          elif patch -p1 --dry-run < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_3_4_5.patch" > /dev/null 2>&1; then
-            patch -p1 < "$WILD_KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_3_4_5.patch"
-          else
-            echo "::error::sysvipc_kabi patches failed to apply due to conflicts; disabling sysvipc to avoid bootloops!"
-            ./scripts/config --file arch/arm64/configs/gki_defconfig \
-                  --disable CONFIG_SYSVIPC
-          fi 
-        fi
+                  --enable CONFIG_POSIX_MQUEUE \
+                  --enable CONFIG_NETFILTER_XT_TARGET_REJECT \
+                  --enable CONFIG_NETFILTER_XT_TARGET_LOG \
+                  --enable CONFIG_NETFILTER_XT_MATCH_RECENT
 
         echo "Other configs added ✅"
         echo "::endgroup::"
@@ -769,13 +845,15 @@ runs:
         echo "::group::Applying build based configs..."
         cd "$COMMON"
 
-        ./scripts/config --file arch/arm64/configs/gki_defconfig \
-          --enable CONFIG_LTO_CLANG_THIN \
-          --enable CONFIG_LTO_CLANG \
-          --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE \
-          --disable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3 \
-          --enable CONFIG_OPTIMIZE_INLINING \
-          --enable CONFIG_TRACEPOINTS
+        if [ "${{ inputs.lto }}" = "Thin" ]; then
+          ./scripts/config --file arch/arm64/configs/gki_defconfig \
+            --enable CONFIG_LTO_CLANG_THIN \
+            --enable CONFIG_LTO_CLANG
+        else
+          ./scripts/config --file arch/arm64/configs/gki_defconfig \
+            --enable CONFIG_LTO_CLANG_FULL \
+            --enable CONFIG_LTO_CLANG
+        fi
 
         # Optimize level config and flags
         if [ "${{ inputs.optimize_level }}" = "O3" ]; then
